alias reset='tput reset'
alias ls='ls -AF --color=auto'
alias l='ls -AFhl --color=auto'
alias rm='rm -v'
alias cp='cp -v'
alias mv='mv -v'
alias shred='shred -zxuvfn20'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias free='free -h'
alias nano='nano -l'
